
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mariadb-depl
  # namespace: ankit
  labels:
    app: maria
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maria
  template:
    metadata:
      labels:
        app: maria
    spec:
          #  nodeSelector:
          #     name: ankit
       containers:
          - name: mariadb-container
            image: mariadb
            ports:
               - containerPort: 3306
            envFrom:
              - configMapRef:
                  name: db-config
              - secretRef:
                  name: maria-secret
            volumeMounts:
            - mountPath: /var/lib/mysql
              name: maria-volume
  volumeClaimTemplates:
  - metadata:
        name: maria-volume
    # reclaimPolicy: Retain
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "local-path"

      resources:
        requests:
          storage: 1Gi

---

apiVersion: v1
kind: Service
metadata:
  name: maria-service
  # namespace: ankit
  labels:
    app: mariasvc
  annotations:
    velero.io/retain-clusterip: "true"
spec:
  selector:
    app: maria
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306

---


apiVersion: batch/v1
kind: Job
metadata:
  name: db-up-job
  # namespace: ankit
  labels:
    app: dbjob
spec:
  # ttlSecondsAfterFinished: 0
  template:
    spec:
      nodeName: luna.pride.improwised.dev
      containers:
      - name: flask-container
        image: ankitjilka31/flask-note:1.3
        command: ["flask", "db", "upgrade"]


        envFrom:
          - configMapRef:
              name: db-config
          - secretRef:
              name: maria-secret

        # env:
        #     - name: DB_HOST
        #       value: maria-service

        #     - name: DB_NAME
        #       value: mydb

        #     - name: DB_USERNAME
        #       value: hello

        #     - name: DB_PASSWORD
        #       value: hello

        #     - name: DB_PORT
        #       value: '3306'

        #     - name: PORT
        #       value: '5000'


      restartPolicy: Never

        # env:
        #   - name: DB_HOST
        #     valueFrom :
        #         configMapKeyRef :
        #             name : db-config
        #             key :  DB_HOST
        #   - name: DB_NAME
        #     valueFrom :
        #         configMapKeyRef :
        #             name : db-config
        #             key :  DB_NAME
        #   - name: DB_USERNAME
        #     valueFrom:
        #         secretKeyRef:
        #             name: maria-secret
        #             key: MARIADB_USER
        #   - name: DB_PASSWORD
        #     valueFrom:
        #         secretKeyRef:
        #             name: maria-secret
        #             key: MARIADB_PASSWORD
        #   - name: DB_PORT
        #     valueFrom :
        #         configMapKeyRef :
        #             name : db-config
        #             key :  DB_PORT
        #   - name: PORT
        #     valueFrom :
        #         configMapKeyRef :
        #             name : db-config
        #             key :  PORT
