apiVersion : v1
kind : ConfigMap
metadata:
  name : db-config
  # namespace: ankit
  labels:
    app: confg
data:
   DB_HOST: maria-service
   DB_NAME: mydb
   DB_PORT: '3306'
   PORT: '5000'
   MARIADB_DATABASE: mydb
   MARIADB_USER: hello

