apiVersion: v1
kind: Secret
metadata:
    name: maria-secret
    # namespace: ankit
    labels:
        app: scrts
type: Opaque
stringData:
    MARIADB_ROOT_PASSWORD: "hello"
    MARIADB_PASSWORD: "hello"
    DB_USERNAME: "hello"
    DB_PASSWORD: "hello"