version: '2.7'

services:
   db:
    image: mariadb:10.2
    environment:
      MYSQL_ROOT_PASSWORD: note
      MYSQL_DATABASE: note
      MYSQL_USER: note
      MYSQL_PASSWORD: note
    logging:
      driver: syslog
    ports:
      - 3305:3306
    restart: on-failure
    volumes:
      - mariadb-notes:/var/lib/mysql

   app:
     image: python_app
     build: .
     environment:
        DB_HOST: db
        DB_PORT: '3306'
        DB_NAME: note
        DB_USERNAME: note
        DB_PASSWORD: note
     ports:
       - 5001:5000
     depends_on:
       - db
       
volumes:
  mariadb-notes:
    driver: local
