name: Linters

on:
  push

jobs:
  linters:
    name: linters
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.10
        timeout-minutes: 5
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install and Run Pre-commit
        timeout-minutes: 5
        uses: pre-commit/action@v3.0.0
